name: '✨ Feature Request'
description: For feature or enhancement requests to expand the library's capabilities.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for bringing your ideas here :pray:.

        The more information you fill in, the better the community can understand your idea.
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem to be solved
      description: Provide a clear and concise description of the challenge you are running into in non-technical terms.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggest a solution
      description: |
        A concise description of your preferred solution. Things to address include:
        - Details of the technical implementation
        - Tradeoffs made in design decisions
        - Caveats and considerations for the future
    validations:
      required: true
